---
name: Caliper test
version: '1.0'
caliper:
    blockchain: fabric
channels:
    mychannel:
        contracts:
          - id: campaign
            language: golang
            version: '1.0'
        created: true
        orderers:
        - orderer.promark.com
        peers:
            peer0.adv0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer0.bus0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer1.adv0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer1.bus0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer2.adv0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer2.bus0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer3.adv0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer3.bus0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer4.adv0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
            peer4.bus0.promark.com:
                chaincodeQuery: true
                endorsingPeer: true
                eventSource: true
                ledgerQuery: true
orderers:
    orderer.promark.com:
        grpcOptions:
            ssl-target-name-override: orderer.promark.com
        tlsCACerts:
            path: ./../organizations/ordererOrganizations/promark.com/tlsca/tlsca.promark.com-cert.pem
        url: grpcs://0.0.0.0:7050
clients:
    peer0.adv0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
            organization: adv0
    peer0.bus0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
            organization: bus0
    peer1.adv0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
            organization: adv0
    peer1.bus0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
            organization: bus0
    peer2.adv0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
            organization: adv0
    peer2.bus0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
            organization: bus0
    peer3.adv0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
            organization: adv0
    peer3.bus0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
            organization: bus0
    peer4.adv0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
                path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
            organization: adv0
    peer4.bus0.promark.com:
        client:
            clientPrivateKey:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
            clientSignedCert:
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
            credentialStore:
                cryptoStore:
                    path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
                path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
            organization: bus0
organizations:
    adv0:
        adminPrivateKey:
            path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
        mspid: adv0MSP
        peers:
        - peer0.adv0.promark.com
        - peer1.adv0.promark.com
        - peer2.adv0.promark.com
        - peer3.adv0.promark.com
        - peer4.adv0.promark.com
        signedCert:
            path: ../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
    bus0:
        adminPrivateKey:
            path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
        mspid: bus0MSP
        peers:
        - peer0.bus0.promark.com
        - peer1.bus0.promark.com
        - peer2.bus0.promark.com
        - peer3.bus0.promark.com
        - peer4.bus0.promark.com
        signedCert:
            path: ../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
peers:
    peer0.adv0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer0.adv0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
        url: grpcs://0.0.0.0:1050
    peer0.bus0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer0.bus0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
        url: grpcs://0.0.0.0:2050
    peer1.adv0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer1.adv0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
        url: grpcs://0.0.0.0:1051
    peer1.bus0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer1.bus0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
        url: grpcs://0.0.0.0:2051
    peer2.adv0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer2.adv0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
        url: grpcs://0.0.0.0:1052
    peer2.bus0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer2.bus0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
        url: grpcs://0.0.0.0:2052
    peer3.adv0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer3.adv0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
        url: grpcs://0.0.0.0:1053
    peer3.bus0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer3.bus0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
        url: grpcs://0.0.0.0:2053
    peer4.adv0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer4.adv0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
        url: grpcs://0.0.0.0:1054
    peer4.bus0.promark.com:
        grpcOptions:
            ssl-target-name-override: peer4.bus0.promark.com
        tlsCACerts:
            path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
        url: grpcs://0.0.0.0:2054
