---
name: Caliper test
version: "1.0"

caliper:
  blockchain: fabric

channels:
  mychannel:
    created: true
    orderers:
      - orderer.promark.com
    peers:
      peer0.adv0.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.adv0.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.adv1.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.adv1.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.bus0.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.bus0.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.bus1.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.bus1.promark.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    contracts:
    - id: campaign
      version: "1.0"
      language: golang

orderers:
  orderer.promark.com:
      url: grpcs://0.0.0.0:7050
      tlsCACerts:
        path: ./../organizations/ordererOrganizations/promark.com/tlsca/tlsca.promark.com-cert.pem
      grpcOptions:
        ssl-target-name-override: orderer.promark.com 

clients:
  peer0.adv0.promark.com:
    client:
      organization: adv0
      credentialStore:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem'
  
  peer1.adv0.promark.com:
    client:
      organization: adv0
      credentialStore:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem'

  peer0.adv1.promark.com:
    client:
      organization: adv1
      credentialStore:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem'

  peer1.adv1.promark.com:
    client:
      organization: adv1
      credentialStore:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem'      

  peer0.bus0.promark.com:
    client:
      organization: bus0
      credentialStore:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem'

  peer1.bus0.promark.com:
    client:
      organization: bus0
      credentialStore:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem'

  peer0.bus1.promark.com:
    client:
      organization: bus1
      credentialStore:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem'

  peer1.bus1.promark.com:
    client:
      organization: bus1
      credentialStore:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/admincerts'
        cryptoStore:
          path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp'
      clientPrivateKey:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk'
      clientSignedCert:
        path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem'

organizations:
  adv0:
    mspid: adv0MSP
    peers: 
      - peer0.adv0.promark.com
      - peer1.adv0.promark.com
    # certificateAuthorities:
    #   - ca.adv0.promark.com
    adminPrivateKey:
      path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk'
    signedCert:
      path: '../organizations/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem'

  adv1:
    mspid: adv1MSP
    peers: 
      - peer0.adv1.promark.com
      - peer1.adv1.promark.com
    # certificateAuthorities:
    #   - ca.adv0.promark.com
    adminPrivateKey:
      path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk'
    signedCert:
      path: '../organizations/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem'


  bus0:
    mspid: bus0MSP
    peers:
      - peer0.bus0.promark.com
      - peer1.bus0.promark.com
    # certificateAuthorities:
    #   - ca.bus0.promark.com
    adminPrivateKey:
      path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk'
    signedCert:
      path: '../organizations/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem'

  bus1:
    mspid: bus1MSP
    peers:
      - peer0.bus1.promark.com
      - peer1.bus1.promark.com
    # certificateAuthorities:
    #   - ca.bus0.promark.com
    adminPrivateKey:
      path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk'
    signedCert:
      path: '../organizations/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem'

peers:
  peer0.adv0.promark.com:
    url: grpcs://0.0.0.0:1050
    tlsCACerts:
      path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer0.adv0.promark.com
  peer1.adv0.promark.com:
    url: grpcs://0.0.0.0:1051
    tlsCACerts:
      path: ./../organizations/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer1.adv0.promark.com
  peer0.adv1.promark.com:
    url: grpcs://0.0.0.0:1150
    tlsCACerts:
      path: ./../organizations/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer0.adv1.promark.com
  peer1.adv1.promark.com:
    url: grpcs://0.0.0.0:1151
    tlsCACerts:
      path: ./../organizations/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer1.adv1.promark.com
  peer0.bus0.promark.com:
    url: grpcs://0.0.0.0:2050
    tlsCACerts:
      path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer0.bus0.promark.com
  peer1.bus0.promark.com:
    url: grpcs://0.0.0.0:2051
    tlsCACerts:
      path: ./../organizations/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer1.bus0.promark.com
  peer0.bus1.promark.com:
    url: grpcs://0.0.0.0:2150
    tlsCACerts:
      path: ./../organizations/peerOrganizations/bus1.promark.com/tlsca/tlsca.bus1.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer0.bus1.promark.com
  peer1.bus1.promark.com:
    url: grpcs://0.0.0.0:2151
    tlsCACerts:
      path: ./../organizations/peerOrganizations/bus1.promark.com/tlsca/tlsca.bus1.promark.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer1.bus1.promark.com

# certificateAuthorities:
#   ca.org1.example.com:
#     url: https://0.0.0.0:1154
#     caName: ca-org1
#     tlsCACerts:
#       path: ./../network/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
#     httpOptions:
#       verify: false
#   ca.org2.example.com:
#     url: https://0.0.0.0:1254
#     caName: ca-org2
#     tlsCACerts:
#       path: ./../network/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
#     httpOptions:
#       verify: false