test:
    name: Campaign-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      # - label: Test query campaign
      #   description:  Test quering campaign benchmark
      #   txDuration: 30
      #   rateControl: 
      #     type: fixed-load
      #     opts:
      #       transactionLoad: 2
      #   workload:
      #     module: ./workloads/queryCampaign.js
      #     arguments:
      #       backups: 10
      #       contractId: campaign
      - label: Create campaign (fixed-load)
        description:  Test creating campaign benchmark(fixed-load)
        txDuration: 30
        rateControl:
            type: fixed-load
            opts:
              transactionLoad: 5
        workload:
          module: ./workloads/createCampaign.js
          arguments:
            contractId: campaign
      - label: Create campaign (fixed-rate)
        description:  Test creating campaign benchmark(fixed-rate)
        txNumber: 3000
        rateControl:
            type: fixed-rate
            opts:
              tps: 200
        workload:
          module: ./workloads/createCampaign.js
          arguments:
            contractId: campaign
      - label: Collect customer data (fixed-rate)
        description:  Test collecting customer data benchmark(fixed-rate)
        txNumber: 3000
        rateControl:
            type: linear-rate
            opts: {
              "startingTps": 100,
              "finishingTps": 500
              }
        workload:
          module: ./workloads/collectData.js
          arguments:
            contractId: campaign

observer:
  type: prometheus
  interval: 5

monitor:
  interval: 1
  type: ['docker', 'prometheus', 'cadvisor']
  docker:
    containers: ['all']
  prometheus:
    url: "http://0.0.0.0:9090"
    metrics:
      ignore: [prometheus, cadvisor, grafana, node-exporter]
      include:
        Endorse Time (s):
          query: rate(endorser_proposal_duration_sum{chaincode="backup"}[5m])/rate(endorser_proposal_duration_count{chaincode="backup"}[5m])
          step: 1
          label: instance
          statistic: avg
