version: '2'
networks:
  promarknet:
    name: promarknet
    driver: bridge

services:
  external.promark.com:
    build:
      context: .
      dockerfile: external-service.dockerfile
    command: /bin/sh /src/ext/run.sh
    container_name: external.promark.com
    environment:
      - API_PORT=5000
      - REDIS_PORT=6379
    networks:
      - promarknet
    expose:
      - 5000
    ports:
      - 3002:5000
    volumes:
      - ../src/ext:/src/ext
      - ../src/internal:/src/internal
  logs.promark.com:
    build:
      context: .
      dockerfile: logs.dockerfile
    command: /bin/sh run.sh
    container_name: logs.promark.com
    environment:
      - LOG_PORT=5003
    networks:
      - promarknet
    ports:
      - 3001:5003
    volumes:
      - ../src/log:/log

  orderer.promark.com:
    container_name: orderer.promark.com
    environment:
      - CORE_OPERATIONS_LISTENADDRESS=orderer.${COMPOSE_PROJECT_NAME}.com:9443
    extends:
      file: docker-compose.base.yml
      service: orderer-base
    networks:
      - promarknet
    ports:
      - 7050:7050
      # - 53732:9443
    volumes:
      - ../channels/mychannel-genesis-2-1.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../credentials/ordererOrganizations/${COMPOSE_PROJECT_NAME}.com/orderers/orderer.${COMPOSE_PROJECT_NAME}.com/msp:/var/hyperledger/orderer/msp
      - ../credentials/ordererOrganizations/${COMPOSE_PROJECT_NAME}.com/orderers/orderer.${COMPOSE_PROJECT_NAME}.com/tls/:/var/hyperledger/orderer/tls

  peer0.adv0.promark.com:
    container_name: peer0.adv0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.adv0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - promarknet
    ports:
      - 5000:7051
      - 5002:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub0.promark.com:
    container_name: peer0.pub0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.pub0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - promarknet
    ports:
      - 6000:7051
      - 6002:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb0.adv0.promark.com:
    container_name: couchdb0.adv0.promark.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - promarknet
    ports:
      - 5001:5984

  couchdb0.pub0.promark.com:
    container_name: couchdb0.pub0.promark.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - promarknet
    ports:
      - 6001:5984

  peer0.adv1.promark.com:
    container_name: peer0.adv1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv1.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.adv1.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv1.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv1.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - promarknet
    ports:
      - 5100:7051
      - 5102:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv1.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv1.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub1.promark.com:
    container_name: peer0.pub1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub1.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.pub1.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub1.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - promarknet
    ports:
      - 6100:7051
      - 6102:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub1.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub1.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb0.adv1.promark.com:
    container_name: couchdb0.adv1.promark.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - promarknet
    ports:
      - 5101:5984

  couchdb0.pub1.promark.com:
    container_name: couchdb0.pub1.promark.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - promarknet
    ports:
      - 6101:5984

  prometheus.promark.com:
    container_name: prometheus.promark.com
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
        - promarknet
    depends_on:
       - cadvisor.promark.com
       - orderer.promark.com
       - peer0.adv0.promark.com
       - peer0.pub0.promark.com

  cadvisor.promark.com:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor.promark.com
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - promarknet
    depends_on:
      - orderer.promark.com
      - peer0.adv0.promark.com
      - peer0.pub0.promark.com


  grafana.promark.com:
    container_name: grafana.promark.com
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - promarknet
    depends_on:
      - prometheus.promark.com