networks:
  test: null
version: '2'
services:
  external.promark.com:
    build:
      context: .
      dockerfile: external-service.dockerfile
    command: /bin/sh /src/ext/run.sh
    container_name: external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - API_PORT=5000
      - REDIS_PORT=6379
    networks:
      - test
    expose:
      - 5000
    ports:
      - 3002:5000
    volumes:
      - ../src/ext:/src/ext
      - ../src/internal:/src/internal

  logs.promark.com:
    build:
      context: .
      dockerfile: logs.dockerfile
    command: /bin/sh run.sh
    container_name: logs.${COMPOSE_PROJECT_NAME}.com
    environment:
      - LOG_PORT=5003
    networks:
      - test
    ports:
      - 3001:5003
    volumes:
      - ../src/log:/log

  orderer.promark.com:
    container_name: orderer.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_OPERATIONS_LISTENADDRESS=orderer.${COMPOSE_PROJECT_NAME}.com:9443
    extends:
      file: docker-compose.base.yml
      service: orderer-base
    networks:
      - test
    ports:
      - 7050:7050
      # - 53732:9443
    volumes:
      - ../channels/mychannel-genesis-1-3.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../credentials/ordererOrganizations/${COMPOSE_PROJECT_NAME}.com/orderers/orderer.${COMPOSE_PROJECT_NAME}.com/msp:/var/hyperledger/orderer/msp
      - ../credentials/ordererOrganizations/${COMPOSE_PROJECT_NAME}.com/orderers/orderer.${COMPOSE_PROJECT_NAME}.com/tls/:/var/hyperledger/orderer/tls

  peer0.adv0.promark.com:
    container_name: peer0.adv0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.adv0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv0.${COMPOSE_PROJECT_NAME}.com:5984

    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5000:7051
      - 5002:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.adv0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb0.adv0.promark.com:
    container_name: couchdb0.adv0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 5001:5984

  peer0.pub0.promark.com:
    container_name: peer0.pub0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.pub0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6000:7051
      - 6002:5000
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb0.pub0.promark.com:
    container_name: couchdb0.pub0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 6001:5984

  peer1.adv0.promark.com:
    container_name: peer1.adv0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb1.adv0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer1.adv0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer1.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.adv0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.adv0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5010:7051
      - 5012:5000
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer1.adv0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer1.adv0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb1.adv0.promark.com:
    container_name: couchdb1.adv0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 5011:5984

  peer1.pub0.promark.com:
    container_name: peer1.pub0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb1.pub0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer1.pub0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer1.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.pub0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.pub0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6010:7051
      - 6012:5000
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer1.pub0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer1.pub0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb1.pub0.promark.com:
    container_name: couchdb1.pub0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 6011:5984

  peer2.adv0.promark.com:
    container_name: peer2.adv0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb2.adv0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer2.adv0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer2.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer2.adv0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.adv0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.adv0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5020:7051
      - 5022:5000
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer2.adv0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${COMPOSE_PROJECT_NAME}.com/peers/peer2.adv0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb2.adv0.promark.com:
    container_name: couchdb2.adv0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 5021:5984

  peer2.pub0.promark.com:
    container_name: peer2.pub0.${COMPOSE_PROJECT_NAME}.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb2.pub0.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer2.pub0.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer2.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer2.pub0.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.pub0.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.pub0.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6020:7051
      - 6022:5000
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer2.pub0.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub0.${COMPOSE_PROJECT_NAME}.com/peers/peer2.pub0.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb2.pub0.promark.com:
    container_name: couchdb2.pub0.${COMPOSE_PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 6021:5984

