networks:
  test: null
version: '2'
services:
  external.promark.com:
    build:
      context: .
      dockerfile: external-service.dockerfile
    command: /bin/sh /src/ext/run.sh
    container_name: external.promark.com
    environment:
      - API_PORT=5000
      - REDIS_PORT=6379
    networks:
      - test
    expose:
      - 5000
    ports:
      - 3002:5000
    volumes:
      - ../src/ext:/src/ext
      - ../src/internal:/src/internal
  logs.promark.com:
    build:
      context: .
      dockerfile: logs.dockerfile
    command: /bin/sh run.sh
    container_name: logs.promark.com
    environment:
      - LOG_PORT=5003
    networks:
      - test
    ports:
      - 3001:5003
    volumes:
      - ../src/log:/log

  orderer.promark.com:
    container_name: orderer.${PROJECT_NAME}.com
    extends:
      file: docker-compose.base.yml
      service: orderer-base
    networks:
      - test
    ports:
      - 7050:7050
    volumes:
      - ../channels/mychannel-genesis-5-1.block:/var/hyperledger/orderer/orderer.genesis.block

  peer0.adv0.promark.com:
    container_name: peer0.adv0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv0.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv0.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv0.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv0.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5000:7051
      - 5002:5000
    volumes:
      - ../credentials/peerOrganizations/adv0.${PROJECT_NAME}.com/peers/peer0.adv0.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${PROJECT_NAME}.com/peers/peer0.adv0.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv1.promark.com:
    container_name: peer0.adv1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv1.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv1.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv1.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv1.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5100:7051
      - 5102:5000
    volumes:
      - ../credentials/peerOrganizations/adv1.${PROJECT_NAME}.com/peers/peer0.adv1.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv1.${PROJECT_NAME}.com/peers/peer0.adv1.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv2.promark.com:
    container_name: peer0.adv2.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv2.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv2.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv2.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv2MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv2.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5200:7051
      - 5202:5000
    volumes:
      - ../credentials/peerOrganizations/adv2.${PROJECT_NAME}.com/peers/peer0.adv2.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv2.${PROJECT_NAME}.com/peers/peer0.adv2.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv3.promark.com:
    container_name: peer0.adv3.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv3.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv3.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv3.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv3MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv3.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5300:7051
      - 5302:5000
    volumes:
      - ../credentials/peerOrganizations/adv3.${PROJECT_NAME}.com/peers/peer0.adv3.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv3.${PROJECT_NAME}.com/peers/peer0.adv3.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv4.promark.com:
    container_name: peer0.adv4.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv4.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv4.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv4.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv4.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv4.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv4.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv4MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv4.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5400:7051
      - 5402:5000
    volumes:
      - ../credentials/peerOrganizations/adv4.${PROJECT_NAME}.com/peers/peer0.adv4.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv4.${PROJECT_NAME}.com/peers/peer0.adv4.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.bus0.promark.com:
    container_name: peer0.bus0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.bus0.promark.com
    environment:
      - CORE_PEER_ID=peer0.bus0.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.bus0.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bus0.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bus0.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bus0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=bus0MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.bus0.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6000:7051
      - 6002:5000
      # - 60000:9443
    volumes:
      - ../credentials/peerOrganizations/bus0.${PROJECT_NAME}.com/peers/peer0.bus0.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/bus0.${PROJECT_NAME}.com/peers/peer0.bus0.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.bus1.promark.com:
    container_name: peer0.bus1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.bus1.promark.com
    environment:
      - CORE_PEER_ID=peer0.bus1.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.bus1.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bus1.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bus1.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bus1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=bus1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.bus1.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6100:7051
      - 6102:5000
      # - 60000:9443
    volumes:
      - ../credentials/peerOrganizations/bus1.${PROJECT_NAME}.com/peers/peer0.bus1.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/bus1.${PROJECT_NAME}.com/peers/peer0.bus1.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.bus2.promark.com:
    container_name: peer0.bus2.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.bus2.promark.com
    environment:
      - CORE_PEER_ID=peer0.bus2.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.bus2.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bus2.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bus2.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bus2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=bus2MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.bus2.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6200:7051
      - 6202:5000
      # - 60000:9443
    volumes:
      - ../credentials/peerOrganizations/bus2.${PROJECT_NAME}.com/peers/peer0.bus2.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/bus2.${PROJECT_NAME}.com/peers/peer0.bus2.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.bus3.promark.com:
    container_name: peer0.bus3.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.bus3.promark.com
    environment:
      - CORE_PEER_ID=peer0.bus3.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.bus3.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bus3.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bus3.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bus3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=bus3MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.bus3.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6300:7051
      - 6302:5000
      # - 60000:9443
    volumes:
      - ../credentials/peerOrganizations/bus3.${PROJECT_NAME}.com/peers/peer0.bus3.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/bus3.${PROJECT_NAME}.com/peers/peer0.bus3.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.bus4.promark.com:
    container_name: peer0.bus4.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.bus4.promark.com
    environment:
      - CORE_PEER_ID=peer0.bu43.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.bus4.${PROJECT_NAME}.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bus4.${PROJECT_NAME}.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bus4.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bus4.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=bus4MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.bus4.promark.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6400:7051
      - 6402:5000
    volumes:
      - ../credentials/peerOrganizations/bus4.${PROJECT_NAME}.com/peers/peer0.bus4.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/bus4.${PROJECT_NAME}.com/peers/peer0.bus4.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  couchdb0.adv0.promark.com:
    container_name: couchdb0.adv0.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5001:5984

  couchdb0.adv1.promark.com:
    container_name: couchdb0.adv1.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5101:5984

  couchdb0.adv2.promark.com:
    container_name: couchdb0.adv2.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5201:5984

  couchdb0.adv3.promark.com:
    container_name: couchdb0.adv3.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5301:5984

  couchdb0.adv4.promark.com:
    container_name: couchdb0.adv4.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5401:5984

  couchdb0.bus0.promark.com:
    container_name: couchdb0.bus0.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6001:5984

  couchdb0.bus1.promark.com:
    container_name: couchdb0.bus1.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6101:5984

  couchdb0.bus2.promark.com:
    container_name: couchdb0.bus2.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6201:5984

  couchdb0.bus3.promark.com:
    container_name: couchdb0.bus3.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    # ports:
    #   - 6301:5984

  couchdb0.bus4.promark.com:
    container_name: couchdb0.bus4.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    # ports:
    #   - 6401:5984