networks:
  test: null
version: '2'
services:
  external.promark.com:
    build:
      context: .
      dockerfile: external-service.dockerfile
    command: /bin/sh /src/ext/run.sh
    container_name: external.promark.com
    environment:
      - API_PORT=5000
      - REDIS_PORT=6379
    networks:
      - test
    expose:
      - 5000
    ports:
      - 3002:5000
    volumes:
      - ../src/ext:/src/ext
      - ../src/internal:/src/internal
  logs.promark.com:
    build:
      context: .
      dockerfile: logs.dockerfile
    command: /bin/sh run.sh
    container_name: logs.promark.com
    environment:
      - LOG_PORT=5003
    networks:
      - test
    ports:
      - 3001:5003
    volumes:
      - ../src/log:/log

  orderer.promark.com:
    container_name: orderer.promark.com
    environment:
      - CORE_OPERATIONS_LISTENADDRESS=orderer.${PROJECT_NAME}.com:9443
    extends:
      file: docker-compose.base.yml
      service: orderer-base
    networks:
      - test
    ports:
      - 7050:7050
      # - 53732:9443
    volumes:
      - ../channels/mychannel-genesis-4-1.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../credentials/ordererOrganizations/${PROJECT_NAME}.com/orderers/orderer.${PROJECT_NAME}.com/msp:/var/hyperledger/orderer/msp
      - ../credentials/ordererOrganizations/${PROJECT_NAME}.com/orderers/orderer.${PROJECT_NAME}.com/tls/:/var/hyperledger/orderer/tls

  peer0.adv0.promark.com:
    container_name: peer0.adv0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv0.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv0.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv0.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv0MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv0.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.adv0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5000:7051
      - 5002:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv0.${PROJECT_NAME}.com/peers/peer0.adv0.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv0.${PROJECT_NAME}.com/peers/peer0.adv0.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv1.promark.com:
    container_name: peer0.adv1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv1.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv1.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv1.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv1.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.adv0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5100:7051
      - 5102:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv1.${PROJECT_NAME}.com/peers/peer0.adv1.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv1.${PROJECT_NAME}.com/peers/peer0.adv1.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv2.promark.com:
    container_name: peer0.adv2.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv2.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv2.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv2.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv2.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.adv0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5200:7051
      - 5202:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv2.${PROJECT_NAME}.com/peers/peer0.adv2.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv2.${PROJECT_NAME}.com/peers/peer0.adv2.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.adv3.promark.com:
    container_name: peer0.adv3.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.adv3.promark.com
    environment:
      - CORE_PEER_ID=peer0.adv3.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.adv3.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adv3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=adv3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.adv3.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.adv0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 5300:7051
      - 5302:5000
      # - 55000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/adv3.${PROJECT_NAME}.com/peers/peer0.adv3.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/adv3.${PROJECT_NAME}.com/peers/peer0.adv3.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub0.promark.com:
    container_name: peer0.pub0.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub0.promark.com
    environment:
      - CORE_PEER_ID=peer0.pub0.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub0.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub0.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub0.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub0MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub0.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.pub0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6000:7051
      - 6002:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub0.${PROJECT_NAME}.com/peers/peer0.pub0.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub0.${PROJECT_NAME}.com/peers/peer0.pub0.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub1.promark.com:
    container_name: peer0.pub1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub1.promark.com
    environment:
      - CORE_PEER_ID=peer0.pub1.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub1.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub1.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub1.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub1.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.pub0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6100:7051
      - 6102:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub1.${PROJECT_NAME}.com/peers/peer0.pub1.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub1.${PROJECT_NAME}.com/peers/peer0.pub1.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub2.promark.com:
    container_name: peer0.pub2.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub2.promark.com
    environment:
      - CORE_PEER_ID=peer0.pub2.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub2.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub2.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub2.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub2.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.pub0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6200:7051
      - 6202:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub2.${PROJECT_NAME}.com/peers/peer0.pub2.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub2.${PROJECT_NAME}.com/peers/peer0.pub2.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls

  peer0.pub3.promark.com:
    container_name: peer0.pub3.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub3.promark.com
    environment:
      - CORE_PEER_ID=peer0.pub3.${PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub3.${PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub3.${PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub3.${PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub3.promark.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - API_PORT=5000
      # - VER_NAME=peer0.pub0.promark.com.log
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6300:7051
      - 6302:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub3.${PROJECT_NAME}.com/peers/peer0.pub3.${PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub3.${PROJECT_NAME}.com/peers/peer0.pub3.${PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls


  couchdb0.adv0.promark.com:
    container_name: couchdb0.adv0.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5001:5984

  couchdb0.adv1.promark.com:
    container_name: couchdb0.adv1.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5101:5984

  couchdb0.adv2.promark.com:
    container_name: couchdb0.adv2.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5201:5984

  couchdb0.adv3.promark.com:
    container_name: couchdb0.adv3.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 5301:5984

  couchdb0.pub0.promark.com:
    container_name: couchdb0.pub0.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6001:5984

  couchdb0.pub1.promark.com:
    container_name: couchdb0.pub1.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6101:5984

  couchdb0.pub2.promark.com:
    container_name: couchdb0.pub2.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6201:5984

  couchdb0.pub3.promark.com:
    container_name: couchdb0.pub3.promark.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1.1
    networks:
      - test
    ports:
      - 6301:5984