global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 10s
  static_configs:
  - targets: ['0.0.0.0:9090']
- job_name: 'hyperledger_metrics'
  scrape_interval: 10s
  static_configs:
  - targets: [
    'peer0.adv0.promark.com:9443',
    'peer0.pub0.promark.com:9443',
    'orderer.promark.com:9443'
  ]

- job_name: 'cadvisor'
  scrape_interval: 5m
  static_configs:
  - targets: ['cadvisor.promark.com:8080']
