version: '2'
networks:
  test: null

services:
  peer0.pub1.promark.com:
    container_name: peer0.pub1.promark.com
    depends_on:
      - orderer.${COMPOSE_PROJECT_NAME}.com
      - couchdb0.pub1.${COMPOSE_PROJECT_NAME}.com
      - external.${COMPOSE_PROJECT_NAME}.com
    environment:
      - CORE_PEER_ID=peer0.pub1.${COMPOSE_PROJECT_NAME}.com
      - CORE_PEER_ADDRESS=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pub1.${COMPOSE_PROJECT_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=pub1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.pub1.${COMPOSE_PROJECT_NAME}.com:5984
    extends:
      file: docker-compose.base.yml
      service: peer-verifier-base
    networks:
      - test
    ports:
      - 6100:7051
      - 6102:5000
      # - 60000:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../credentials/peerOrganizations/pub1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub1.${COMPOSE_PROJECT_NAME}.com/msp:/etc/hyperledger/fabric/msp
      - ../credentials/peerOrganizations/pub1.${COMPOSE_PROJECT_NAME}.com/peers/peer0.pub1.${COMPOSE_PROJECT_NAME}.com/tls:/etc/hyperledger/fabric/tls


  couchdb0.pub1.promark.com:
    container_name: couchdb0.pub1.promark.com
    extends:
      file: docker-compose.base.yml
      service: couchdb-base
    networks:
      - test
    ports:
      - 6101:5984
