---
name: Caliper test
version: "1.0"
caliper:
  blockchain: fabric
channels:
  mychannel:
    contracts:
      - id: campaign
        language: golang
        version: "1.0"
      - id: proof
        language: golang
        version: "1.0"
      - id: poc
        language: golang
        version: "1.0"
    created: true
    orderers:
      - orderer.promark.com
    peers:
      peer0.adv0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.pub0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.adv1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.pub1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.adv2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.pub2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.adv3.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer0.pub3.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.adv0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.pub0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.adv1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.pub1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.adv2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.pub2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.adv3.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

      peer1.pub3.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true

orderers:
  orderer.promark.com:
    grpcOptions:
      ssl-target-name-override: orderer.promark.com
    tlsCACerts:
      path: ../../credentials/ordererOrganizations/promark.com/tlsca/tlsca.promark.com-cert.pem
    url: grpcs://0.0.0.0:7050

clients:
  peer0.adv0.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
        path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
      organization: adv0

  peer0.pub0.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp/signcerts/Admin@pub0.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp
        path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp/admincerts
      organization: pub0

  peer0.adv1.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp
        path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/admincerts
      organization: adv1

  peer0.pub1.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp/signcerts/Admin@pub1.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp
        path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp/admincerts
      organization: pub1

  peer0.adv2.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/signcerts/Admin@adv2.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp
        path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/admincerts
      organization: adv2

  peer0.pub2.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp/signcerts/Admin@pub2.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp
        path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp/admincerts
      organization: pub2

  peer0.adv3.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp/signcerts/Admin@adv3.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp
        path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp/admincerts
      organization: adv3

  peer0.pub3.promark.com:
    client:
      clientPrivateKey:
        path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp/signcerts/Admin@pub3.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp
        path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp/admincerts
      organization: pub3

organizations:
  adv0:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
    mspid: adv0MSP
    peers:
      - peer0.adv0.promark.com
      - peer1.adv0.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem

  pub0:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp/keystore/priv_sk
    mspid: pub0MSP
    peers:
      - peer0.pub0.promark.com
      - peer1.pub0.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/pub0.promark.com/users/Admin@pub0.promark.com/msp/signcerts/Admin@pub0.promark.com-cert.pem

  adv1:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk
    mspid: adv1MSP
    peers:
      - peer0.adv1.promark.com
      - peer1.adv1.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem

  pub1:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp/keystore/priv_sk
    mspid: pub1MSP
    peers:
      - peer0.pub1.promark.com
      - peer1.pub1.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/pub1.promark.com/users/Admin@pub1.promark.com/msp/signcerts/Admin@pub1.promark.com-cert.pem

  adv2:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/keystore/priv_sk
    mspid: adv2MSP
    peers:
      - peer0.adv2.promark.com
      - peer1.adv2.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/signcerts/Admin@adv2.promark.com-cert.pem

  pub2:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp/keystore/priv_sk
    mspid: pub2MSP
    peers:
      - peer0.pub2.promark.com
      - peer1.pub2.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/pub2.promark.com/users/Admin@pub2.promark.com/msp/signcerts/Admin@pub2.promark.com-cert.pem

  adv3:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp/keystore/priv_sk
    mspid: adv3MSP
    peers:
      - peer0.adv3.promark.com
      - peer1.adv3.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/adv3.promark.com/users/Admin@adv3.promark.com/msp/signcerts/Admin@adv3.promark.com-cert.pem

  pub3:
    adminPrivateKey:
      path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp/keystore/priv_sk
    mspid: pub3MSP
    peers:
      - peer0.pub3.promark.com
      - peer1.pub3.promark.com
    signedCert:
      path: ../../credentials/peerOrganizations/pub3.promark.com/users/Admin@pub3.promark.com/msp/signcerts/Admin@pub3.promark.com-cert.pem

peers:
  peer0.adv0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv0.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
    url: grpcs://0.0.0.0:5000

  peer0.pub0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.pub0.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub0.promark.com/tlsca/tlsca.pub0.promark.com-cert.pem
    url: grpcs://0.0.0.0:6000

  peer0.adv1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv1.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
    url: grpcs://0.0.0.0:5100

  peer0.pub1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.pub1.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub1.promark.com/tlsca/tlsca.pub1.promark.com-cert.pem
    url: grpcs://0.0.0.0:6100

  peer0.adv2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv2.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv2.promark.com/tlsca/tlsca.adv2.promark.com-cert.pem
    url: grpcs://0.0.0.0:5200

  peer0.pub2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.pub2.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub2.promark.com/tlsca/tlsca.pub2.promark.com-cert.pem
    url: grpcs://0.0.0.0:6200

  peer0.adv3.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv3.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv3.promark.com/tlsca/tlsca.adv3.promark.com-cert.pem
    url: grpcs://0.0.0.0:5300

  peer0.pub3.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.pub3.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub3.promark.com/tlsca/tlsca.pub3.promark.com-cert.pem
    url: grpcs://0.0.0.0:6300

  peer1.adv0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.adv0.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
    url: grpcs://0.0.0.0:5010

  peer1.pub0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.pub0.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub0.promark.com/tlsca/tlsca.pub0.promark.com-cert.pem
    url: grpcs://0.0.0.0:6010

  peer1.adv1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.adv1.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
    url: grpcs://0.0.0.0:5110

  peer1.pub1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.pub1.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub1.promark.com/tlsca/tlsca.pub1.promark.com-cert.pem
    url: grpcs://0.0.0.0:6110

  peer1.adv2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.adv2.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv2.promark.com/tlsca/tlsca.adv2.promark.com-cert.pem
    url: grpcs://0.0.0.0:5210

  peer1.pub2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.pub2.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub2.promark.com/tlsca/tlsca.pub2.promark.com-cert.pem
    url: grpcs://0.0.0.0:6210

  peer1.adv3.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.adv3.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/adv3.promark.com/tlsca/tlsca.adv3.promark.com-cert.pem
    url: grpcs://0.0.0.0:5310

  peer1.pub3.promark.com:
    grpcOptions:
      ssl-target-name-override: peer1.pub3.promark.com
    tlsCACerts:
      path: ../../credentials/peerOrganizations/pub3.promark.com/tlsca/tlsca.pub3.promark.com-cert.pem
    url: grpcs://0.0.0.0:6310