Organizations:
  - &OrdererOrg
    Name: ordererMSP
    ID: ordererMSP
    MSPDir: ../organizations/ordererOrganizations/promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.admin')"

  - &Adv0
    Name: adv0MSP
    ID: adv0MSP
    MSPDir: ../organizations/peerOrganizations/adv0.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv0MSP.admin', 'adv0MSP.peer', 'adv0MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv0MSP.admin', 'adv0MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv0MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv0MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    # AnchorPeers:
    #   - Host: peer0.adv0.promark.com
    #     Port: 1050

  - &Adv1
    Name: adv1MSP
    ID: adv1MSP
    MSPDir: ../organizations/peerOrganizations/adv1.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv1MSP.admin', 'adv1MSP.peer', 'adv1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv1MSP.admin', 'adv1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv1MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    # AnchorPeers:
    #   - Host: peer0.adv1.promark.com
    #     Port: 1060
  - &Adv2
    Name: adv2MSP
    ID: adv2MSP
    MSPDir: ../organizations/peerOrganizations/adv2.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv2MSP.admin', 'adv2MSP.peer', 'adv2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv2MSP.admin', 'adv2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv2MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050

  - &Pub0
    Name: pub0MSP
    ID: pub0MSP
    MSPDir: ../organizations/peerOrganizations/pub0.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('pub0MSP.admin', 'pub0MSP.peer', 'pub0MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('pub0MSP.admin', 'pub0MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('pub0MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('pub0MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    # AnchorPeers defines the location of peers which can be used for
        # cross-org gossip communication. Note, this value is only encoded in
        # the genesis block in the Application section context.
    # AnchorPeers:
    #     - Host: peer0.pub0.promark.com
    #       Port: 2050

  - &Pub1
    Name: pub1MSP
    ID: pub1MSP
    MSPDir: ../organizations/peerOrganizations/pub1.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('pub1MSP.admin', 'pub1MSP.peer', 'pub1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('pub1MSP.admin', 'pub1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('pub1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('pub1MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
  - &Pub2
    Name: pub2MSP
    ID: pub2MSP
    MSPDir: ../organizations/peerOrganizations/pub2.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('pub2MSP.admin', 'pub2MSP.peer', 'pub2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('pub2MSP.admin', 'pub2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('pub2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('pub2MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
  #   # AnchorPeers:
  #   # - Host: peer0.pub1.promark.com
  #   #   Port: 2060

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.promark.com:7050

  EtcdRaft:
    Consenters:
      - Host: orderer.promark.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/promark.com/orderers/orderer.promark.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/promark.com/orderers/orderer.promark.com/tls/server.crt

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # Who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Adv0
          - *Pub0
          - *Adv1
          - *Pub1
          - *Adv2
          - *Pub2

  TwoOrgsChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Adv0
        - *Pub0
        - *Adv1
        - *Pub1
        - *Adv2
        - *Pub2

      Capabilities:
        <<: *ApplicationCapabilities
