Organizations:
  - &OrdererOrg
    Name: ordererMSP
    ID: ordererMSP
    MSPDir: ../organizations/ordererOrganizations/promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.admin')"

  - &Adv0
    Name: adv0MSP
    ID: adv0MSP
    MSPDir: ../organizations/peerOrganizations/adv0.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv0MSP.admin', 'adv0MSP.peer', 'adv0MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv0MSP.admin', 'adv0MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv0MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv0MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv0.promark.com
        Port: 1050

  - &Adv1
    Name: adv1MSP
    ID: adv1MSP
    MSPDir: ../organizations/peerOrganizations/adv1.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv1MSP.admin', 'adv1MSP.peer', 'adv1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv1MSP.admin', 'adv1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv1MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv1.promark.com
        Port: 1150
  
  - &Adv2
    Name: adv2MSP
    ID: adv2MSP
    MSPDir: ../organizations/peerOrganizations/adv2.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv2MSP.admin', 'adv2MSP.peer', 'adv2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv2MSP.admin', 'adv2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv2MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv2.promark.com
        Port: 1250

  - &Adv3
    Name: adv3MSP
    ID: adv3MSP
    MSPDir: ../organizations/peerOrganizations/adv3.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv3MSP.admin', 'adv3MSP.peer', 'adv3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv3MSP.admin', 'adv3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv3MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv3.promark.com
        Port: 1350

  - &Adv4
    Name: adv4MSP
    ID: adv4MSP
    MSPDir: ../organizations/peerOrganizations/adv4.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv4MSP.admin', 'adv4MSP.peer', 'adv4MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv4MSP.admin', 'adv4MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv4MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv4.promark.com
        Port: 1450

  - &Adv5
    Name: adv5MSP
    ID: adv5MSP
    MSPDir: ../organizations/peerOrganizations/adv5.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv5MSP.admin', 'adv5MSP.peer', 'adv5MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv5MSP.admin', 'adv5MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv5MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv5MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv5.promark.com
        Port: 1550

  - &Adv6
    Name: adv6MSP
    ID: adv6MSP
    MSPDir: ../organizations/peerOrganizations/adv6.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv6MSP.admin', 'adv6MSP.peer', 'adv6MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv6MSP.admin', 'adv6MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv6MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv6MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv6.promark.com
        Port: 1650

  - &Adv7
    Name: adv7MSP
    ID: adv7MSP
    MSPDir: ../organizations/peerOrganizations/adv7.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv7MSP.admin', 'adv7MSP.peer', 'adv7MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv7MSP.admin', 'adv7MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv7MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv7MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv7.promark.com
        Port: 1750

  - &Adv8
    Name: adv8SP
    ID: adv8SP
    MSPDir: ../organizations/peerOrganizations/adv8.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('adv8SP.admin', 'adv8SP.peer', 'adv8SP.client')"
      Writers:
        Type: Signature
        Rule: "OR('adv8SP.admin', 'adv8SP.client')"
      Admins:
        Type: Signature
        Rule: "OR('adv8SP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('adv8SP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
      - Host: peer0.adv8.promark.com
        Port: 1850

  - &Bus0
    Name: bus0MSP
    ID: bus0MSP
    MSPDir: ../organizations/peerOrganizations/bus0.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus0MSP.admin', 'bus0MSP.peer', 'bus0MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus0MSP.admin', 'bus0MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus0MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus0MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    # AnchorPeers defines the location of peers which can be used for
        # cross-org gossip communication. Note, this value is only encoded in
        # the genesis block in the Application section context.
    AnchorPeers:
        - Host: peer0.bus0.promark.com
          Port: 2050

  - &Bus1
    Name: bus1MSP
    ID: bus1MSP
    MSPDir: ../organizations/peerOrganizations/bus1.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus1MSP.admin', 'bus1MSP.peer', 'bus1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus1MSP.admin', 'bus1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus1MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus1.promark.com
      Port: 2150
  
  - &Bus2
    Name: bus2MSP
    ID: bus2MSP
    MSPDir: ../organizations/peerOrganizations/bus2.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus2MSP.admin', 'bus2MSP.peer', 'bus2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus2MSP.admin', 'bus2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus2MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus2.promark.com
      Port: 2250

  - &Bus3
    Name: bus3MSP
    ID: bus3MSP
    MSPDir: ../organizations/peerOrganizations/bus3.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus3MSP.admin', 'bus3MSP.peer', 'bus3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus3MSP.admin', 'bus3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus3MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus3.promark.com
      Port: 2350

  - &Bus4
    Name: bus4MSP
    ID: bus4MSP
    MSPDir: ../organizations/peerOrganizations/bus4.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus4MSP.admin', 'bus4MSP.peer', 'bus4MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus4MSP.admin', 'bus4MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus4MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus4.promark.com
      Port: 2450

  - &Bus5
    Name: bus5MSP
    ID: bus5MSP
    MSPDir: ../organizations/peerOrganizations/bus5.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus5MSP.admin', 'bus5MSP.peer', 'bus5MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus5MSP.admin', 'bus5MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus5MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus5MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus5.promark.com
      Port: 2550

  - &Bus6
    Name: bus6MSP
    ID: bus6MSP
    MSPDir: ../organizations/peerOrganizations/bus6.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus6MSP.admin', 'bus6MSP.peer', 'bus6MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus6MSP.admin', 'bus6MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus6MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus6MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus6.promark.com
      Port: 2650

  - &Bus7
    Name: bus7MSP
    ID: bus7MSP
    MSPDir: ../organizations/peerOrganizations/bus7.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus7MSP.admin', 'bus7MSP.peer', 'bus7MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus7MSP.admin', 'bus7MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus7MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus7MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus7.promark.com
      Port: 2750

  - &Bus8
    Name: bus8MSP
    ID: bus8MSP
    MSPDir: ../organizations/peerOrganizations/bus8.promark.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('bus8MSP.admin', 'bus8MSP.peer', 'bus8MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('bus8MSP.admin', 'bus8MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('bus8MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('bus8MSP.peer')"
    OrdererEndpoints:
      - orderer.promark.com:7050
    AnchorPeers:
    - Host: peer0.bus8.promark.com
      Port: 2850

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.promark.com:7050

  EtcdRaft:
    Consenters:
      - Host: orderer.promark.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/promark.com/orderers/orderer.promark.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/promark.com/orderers/orderer.promark.com/tls/server.crt

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # Who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Adv0
          - *Bus0
          - *Adv1
          - *Bus1
          - *Adv2
          - *Bus2
          - *Adv3
          - *Bus3
          - *Adv4
          - *Bus4
          - *Adv5
          - *Bus5
          - *Adv6
          - *Bus6
          - *Adv7
          - *Bus7
          - *Adv8
          - *Bus8
  TwoOrgsChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Adv0
        - *Bus0
        - *Adv1
        - *Bus1
        - *Adv2
        - *Bus2
        - *Adv3
        - *Bus3
        - *Adv4
        - *Bus4
        - *Adv5
        - *Bus5
        - *Adv6
        - *Bus6
        - *Adv7
        - *Bus7
        - *Adv8
        - *Bus8
      Capabilities:
        <<: *ApplicationCapabilities
