---
name: Caliper test
version: "1.0"
caliper:
  blockchain: fabric
channels:
  mychannel:
    contracts:
      - id: campaign
        language: golang
        version: "1.0"
      - id: proof
        language: golang
        version: "1.0"
    created: true
    orderers:
      - orderer.promark.com
    peers:
      peer0.adv0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.adv1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.adv2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.bus0.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.bus1.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.bus2.promark.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      # peer1.adv0.promark.com:
      #     chaincodeQuery: true
      #     endorsingPeer: true
      #     eventSource: true
      #     ledgerQuery: true
      # peer1.adv1.promark.com:
      #     chaincodeQuery: true
      #     endorsingPeer: true
      #     eventSource: true
      #     ledgerQuery: true
      # peer1.bus0.promark.com:
      #     chaincodeQuery: true
      #     endorsingPeer: true
      #     eventSource: true
      #     ledgerQuery: true
      # peer1.bus1.promark.com:
      #     chaincodeQuery: true
      #     endorsingPeer: true
      #     eventSource: true
      #     ledgerQuery: true
orderers:
  orderer.promark.com:
    grpcOptions:
      ssl-target-name-override: orderer.promark.com
    tlsCACerts:
      path: ./../credentials/ordererOrganizations/promark.com/tlsca/tlsca.promark.com-cert.pem
    url: grpcs://0.0.0.0:7050
clients:
  peer0.adv0.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
        path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
      organization: adv0
  peer0.adv1.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp
        path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/admincerts
      organization: adv1
  peer0.adv2.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/signcerts/Admin@adv2.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp
        path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/admincerts
      organization: adv2
  peer0.bus0.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
        path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
      organization: bus0
  peer0.bus1.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp
        path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/admincerts
      organization: bus1
  peer0.bus2.promark.com:
    client:
      clientPrivateKey:
        path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp/signcerts/Admin@bus2.promark.com-cert.pem
      credentialStore:
        cryptoStore:
          path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp
        path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp/admincerts
      organization: bus2
  # peer1.adv0.promark.com:
  #     client:
  #         clientPrivateKey:
  #             path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
  #         clientSignedCert:
  #             path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
  #         credentialStore:
  #             cryptoStore:
  #                 path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp
  #             path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/admincerts
  #         organization: adv0
  # peer1.adv1.promark.com:
  #     client:
  #         clientPrivateKey:
  #             path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk
  #         clientSignedCert:
  #             path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem
  #         credentialStore:
  #             cryptoStore:
  #                 path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp
  #             path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/admincerts
  #         organization: adv1
  # peer1.bus0.promark.com:
  #     client:
  #         clientPrivateKey:
  #             path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
  #         clientSignedCert:
  #             path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
  #         credentialStore:
  #             cryptoStore:
  #                 path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp
  #             path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/admincerts
  #         organization: bus0
  # peer1.bus1.promark.com:
  #     client:
  #         clientPrivateKey:
  #             path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk
  #         clientSignedCert:
  #             path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem
  #         credentialStore:
  #             cryptoStore:
  #                 path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp
  #             path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/admincerts
  #         organization: bus1
organizations:
  adv0:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/keystore/priv_sk
    mspid: adv0MSP
    peers:
      - peer0.adv0.promark.com
    # - peer1.adv0.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/adv0.promark.com/users/Admin@adv0.promark.com/msp/signcerts/Admin@adv0.promark.com-cert.pem
  adv1:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/keystore/priv_sk
    mspid: adv1MSP
    peers:
      - peer0.adv1.promark.com
      # - peer1.adv1.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/adv1.promark.com/users/Admin@adv1.promark.com/msp/signcerts/Admin@adv1.promark.com-cert.pem
  adv2:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/keystore/priv_sk
    mspid: adv2MSP
    peers:
      - peer0.adv2.promark.com
      # - peer1.adv1.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/adv2.promark.com/users/Admin@adv2.promark.com/msp/signcerts/Admin@adv2.promark.com-cert.pem
  bus0:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/keystore/priv_sk
    mspid: bus0MSP
    peers:
      - peer0.bus0.promark.com
    # - peer1.bus0.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/bus0.promark.com/users/Admin@bus0.promark.com/msp/signcerts/Admin@bus0.promark.com-cert.pem
  bus1:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/keystore/priv_sk
    mspid: bus1MSP
    peers:
      - peer0.bus1.promark.com
      # - peer1.bus1.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/bus1.promark.com/users/Admin@bus1.promark.com/msp/signcerts/Admin@bus1.promark.com-cert.pem
  bus2:
    adminPrivateKey:
      path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp/keystore/priv_sk
    mspid: bus1MSP
    peers:
      - peer0.bus2.promark.com
      # - peer1.bus1.promark.com
    signedCert:
      path: ../credentials/peerOrganizations/bus2.promark.com/users/Admin@bus2.promark.com/msp/signcerts/Admin@bus2.promark.com-cert.pem
peers:
  peer0.adv0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv0.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
    url: grpcs://0.0.0.0:5000
  peer0.adv1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv1.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
    url: grpcs://0.0.0.0:5100
  peer0.adv2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.adv2.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/adv2.promark.com/tlsca/tlsca.adv2.promark.com-cert.pem
    url: grpcs://0.0.0.0:5200
  peer0.bus0.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.bus0.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
    url: grpcs://0.0.0.0:6000
  peer0.bus1.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.bus1.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/bus1.promark.com/tlsca/tlsca.bus1.promark.com-cert.pem
    url: grpcs://0.0.0.0:6100
  peer0.bus2.promark.com:
    grpcOptions:
      ssl-target-name-override: peer0.bus2.promark.com
    tlsCACerts:
      path: ./../credentials/peerOrganizations/bus2.promark.com/tlsca/tlsca.bus2.promark.com-cert.pem
    url: grpcs://0.0.0.0:6200
  # peer1.adv0.promark.com:
  #     grpcOptions:
  #         ssl-target-name-override: peer1.adv0.promark.com
  #     tlsCACerts:
  #         path: ./../credentials/peerOrganizations/adv0.promark.com/tlsca/tlsca.adv0.promark.com-cert.pem
  #     url: grpcs://0.0.0.0:6100
  # peer1.adv1.promark.com:
  #     grpcOptions:
  #         ssl-target-name-override: peer1.adv1.promark.com
  #     tlsCACerts:
  #         path: ./../credentials/peerOrganizations/adv1.promark.com/tlsca/tlsca.adv1.promark.com-cert.pem
  #     url: grpcs://0.0.0.0:1061
  # peer1.bus0.promark.com:
  #     grpcOptions:
  #         ssl-target-name-override: peer1.bus0.promark.com
  #     tlsCACerts:
  #         path: ./../credentials/peerOrganizations/bus0.promark.com/tlsca/tlsca.bus0.promark.com-cert.pem
  #     url: grpcs://0.0.0.0:2051
  # peer1.bus1.promark.com:
  #     grpcOptions:
  #         ssl-target-name-override: peer1.bus1.promark.com
  #     tlsCACerts:
  #         path: ./../credentials/peerOrganizations/bus1.promark.com/tlsca/tlsca.bus1.promark.com-cert.pem
  #     url: grpcs://0.0.0.0:2061
